Fix bug in IPv6 default route setting
A buggy if check causes the code to attempt setting the IPv6 default
route through an IPv4 gateway causing PAPI to produce the following
error:

    TypeError: object of type 'IPv4Address' has no len()

Change-Id: Ia455cb983f26f171994e45d30ac0575300fdbdb3
Closes-Bug: #1899772