Fix FIP failure with python3 and VPP 19.08.1
The nat44_add_del_static_mapping API expects a binary/bytes type for
the local and remote IP address whereas what is passed to it is an
str object which causes PAPI to produce the following error:

vpp_papi.vpp_serializer.VPPSerializerValueError: Fixed list length
error for "vl_api_ip4_address_t", got: 16 expected: 4

Change-Id: I4a801d44bdc9079454e693eb94fabb2784b98f5e
Closes-Bug: #1855863