Fix for sw_interface_tag_add_del change in 19.08.1
The sw_interface_tag_add_del API's 'tag' field's type has changed
from the earlier u8/binary to the new string type. Since the ML2
agent tries to set a binary tag, this causes port binding requests
to fail with the following error:

AttributeError: 'bytes' object has no attribute 'encode'

Change-Id: I4068072f9337e1cfa79898e5b089f4e6219bb27e
Closes-Bug: #1855455